namespace FurAffinityFs.Models

type Category =
    | ``All`` = 1
    | ``Artwork_Digital`` = 2
    | ``Artwork_Traditional`` = 3
    | ``Cellshading`` = 4
    | ``Crafting`` = 5
    | ``Designs`` = 6
    | ``Flash`` = 7
    | ``Fursuiting`` = 8
    | ``Icons`` = 9
    | ``Mosaics`` = 10
    | ``Photography`` = 11
    | ``Sculpting`` = 12
    | ``Story`` = 13
    | ``Poetry`` = 14
    | ``Prose`` = 15
    | ``Music`` = 16
    | ``Podcasts`` = 17
    | ``Skins`` = 18
    | ``Handhelds`` = 19
    | ``Resources`` = 20
    | ``Adoptables`` = 21
    | ``Auctions`` = 22
    | ``Contests`` = 23
    | ``Current_Events`` = 24
    | ``Desktops`` = 25
    | ``Stockart`` = 26
    | ``Screenshots`` = 27
    | ``Scraps`` = 28
    | ``Wallpaper`` = 29
    | ``YCH_or_Sale`` = 30
    | ``Other`` = 31
